src/Rottenwood/BarchartBundle/Entity/Symbol.php
<?php

namespace Rottenwood\BarchartBundle\Entity;

/**
 * Торговые символы
 */
abstract class Symbol {

    const SYMBOL_FUTURES_CORN = 1;
    const SYMBOL_FUTURES_CRUDEOIL = 2;
    const SYMBOL_FUTURES_DJMINI = 3;
    const SYMBOL_FUTURES_EMINI = 4;
    const SYMBOL_FUTURES_GOLD = 5;
    const SYMBOL_FUTURES_NATURALGAS = 6;
    const SYMBOL_FUTURES_SILVER = 7;
    const SYMBOL_FUTURES_SOYBEANS = 8;
    const SYMBOL_FUTURES_WHEAT = 9;

    const SYMBOL_FOREX_AUDUSD = 50;
    const SYMBOL_FOREX_EURUSD = 51;
    const SYMBOL_FOREX_GBPUSD = 52;
    const SYMBOL_FOREX_USDCAD = 53;
    const SYMBOL_FOREX_USDCHF = 54;
    const SYMBOL_FOREX_USDJPY = 55;

    /**
     * Получение массива названий сущностей для торговых символов
     * @return array
     */
    public static function getSymbolName() {
        return array(
            self::SYMBOL_FUTURES_CORN       => 'Corn',
            self::SYMBOL_FUTURES_CRUDEOIL   => 'CrudeOil',
            self::SYMBOL_FUTURES_DJMINI     => 'DJMini',
            self::SYMBOL_FUTURES_EMINI      => 'Emini',
            self::SYMBOL_FUTURES_GOLD       => 'Gold',
            self::SYMBOL_FUTURES_NATURALGAS => 'NaturalGas',
            self::SYMBOL_FUTURES_SILVER     => 'Silver',
            self::SYMBOL_FUTURES_SOYBEANS   => 'Soybeans',
            self::SYMBOL_FUTURES_WHEAT      => 'Wheat',

            self::SYMBOL_FOREX_AUDUSD       => 'AUDUSD',
            self::SYMBOL_FOREX_EURUSD       => 'EURUSD',
            self::SYMBOL_FOREX_GBPUSD       => 'GBPUSD',
            self::SYMBOL_FOREX_USDCAD       => 'USDCAD',
            self::SYMBOL_FOREX_USDCHF       => 'USDCHF',
            self::SYMBOL_FOREX_USDJPY       => 'USDJPY',
        );
    }

    /**
     * Получение массива русских названий сущностей для торговых символов
     * @return array
     */
    public static function getRussianSymbolName() {
        return array(
            self::SYMBOL_FUTURES_CORN       => 'Кукуруза',
            self::SYMBOL_FUTURES_CRUDEOIL   => 'Нефть марки WTI',
            self::SYMBOL_FUTURES_DJMINI     => 'Индекс DowJones mini',
            self::SYMBOL_FUTURES_EMINI      => 'Индекс S&P mini',
            self::SYMBOL_FUTURES_GOLD       => 'Золото',
            self::SYMBOL_FUTURES_NATURALGAS => 'Природный газ',
            self::SYMBOL_FUTURES_SILVER     => 'Серебро',
            self::SYMBOL_FUTURES_SOYBEANS   => 'Соевые бобы',
            self::SYMBOL_FUTURES_WHEAT      => 'Пшеница',

            self::SYMBOL_FOREX_AUDUSD       => 'Австралийский доллар к Доллару США',
            self::SYMBOL_FOREX_EURUSD       => 'Евро к Доллару США',
            self::SYMBOL_FOREX_GBPUSD       => 'Британский фунт к Доллару США',
            self::SYMBOL_FOREX_USDCAD       => 'Доллар США к Канадскому доллару',
            self::SYMBOL_FOREX_USDCHF       => 'Доллар США к Швейцарскому франку',
            self::SYMBOL_FOREX_USDJPY       => 'Доллар США к Японской йене',
        );
    }
}

src/Rottenwood/BarchartBundle/Controller/DefaultController.php
<?php

namespace Rottenwood\BarchartBundle\Controller;

use Rottenwood\BarchartBundle\Entity\Strategy;
use Rottenwood\BarchartBundle\Form\StrategyType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;

class DefaultController extends Controller {

    /**
     * @Route("/", name="index")
     * @Template()
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function indexAction() {
        $em = $this->getDoctrine()->getManager();
        $user = $this->getUser();

        return [
            'haveStrategies' => count($em->getRepository('RottenwoodBarchartBundle:Strategy')->findByAuthor($user)) > 0,
            'haveAccounts'   =>
                count($em->getRepository('RottenwoodBarchartBundle:TradeAccount')->findByAnalitic($user)) > 0,
        ];
    }

    /**
     * @Route("/strategy/create", name="strategy.create")
     * @Template("RottenwoodBarchartBundle:Default:editStrategy.html.twig")
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function createStrategyAction(Request $request) {
        $em = $this->getDoctrine()->getEntityManager();

        $strategy = new Strategy();
        $strategy->setAuthor($this->getUser());

        $isStrategyNew = true;

        $form = $this->createForm(new StrategyType($isStrategyNew), $strategy, ['cascade_validation' => true]);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $strategy = $form->getData();

            $em->persist($strategy);
            $em->flush();

            return $this->redirectToRoute('account.create');
        }

        return [
            'form' => $form->createView(),
        ];
    }

    /**
     * Список стратегий пользователя
     * @Route("/strategy/list", name="strategy.list")
     * @Template()
     * @return array
     */
    public function listStrategiesAction() {
        $em = $this->getDoctrine()->getManager();
        $strategies = $em->getRepository('RottenwoodBarchartBundle:Strategy')->findByAuthor($this->getUser());

        if (!$strategies) {
            return $this->redirectToRoute('index');
        }

        return [
            'strategies' => $strategies,
        ];
    }

    /**
     * Рейтинг открытых стратегий
     * @Route("/strategy/rating", name="strategy.rating")
     * @Template()
     * @return array
     */
    public function showStrategyRatingAction() {
        $em = $this->getDoctrine()->getManager();
        $strategies = $em->getRepository('RottenwoodBarchartBundle:Strategy')->findByIsPrivate(false);

        if (!$strategies) {
            return $this->redirectToRoute('index');
        }

        return [
            'strategies' => $strategies,
        ];
    }

    /**
     * Редактирование стратегий
     * @Route("/strategy/edit/{id}", requirements={"id"="\d+"}, name="strategy.edit")
     * @Template()
     * @ParamConverter("id", class="RottenwoodBarchartBundle:Strategy")
     * @param Request  $request
     * @param Strategy $strategy
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function editStrategyAction(Request $request, Strategy $strategy) {

        if ($this->getUser()->getId() != $strategy->getAuthor()->getId()) {
            return $this->redirectToRoute('strategy.list');
        }

        $em = $this->getDoctrine()->getEntityManager();

        $form = $this->createForm(new StrategyType(), $strategy, ['cascade_validation' => true]);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $strategy = $form->getData();

            $em->persist($strategy);
            $em->flush();

            return $this->redirectToRoute('strategy.list');
        }

        return [
            'form' => $form->createView(),
        ];
    }

    /**
     * Бэктестинг стратегии
     * @Route("/test/{id}", requirements={"id"="\d+"}, name="strategy.test")
     * @Template()
     * @ParamConverter("id", class="RottenwoodBarchartBundle:Strategy")
     * @param Strategy $strategy
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function testStrategyAction(Strategy $strategy) {
        if ($strategy->isPrivate() && $strategy->getAuthor() !== $this->getUser()) {
            return [
                'strategyIsPrivate' => $strategy->getId(),
            ];
        }

        $analizer = $this->get('barchart.analizer');
        $trades = $analizer->testStrategy($strategy);

        $lastPrice = $analizer->getLastPrice($strategy);
        $profit = $analizer->calculatePercentProfit($trades);

        return [
            'strategy'             => $strategy,
            'trades'               => $trades,
            'currentPrice'         => $lastPrice ? $lastPrice->getPrice() : 0,
            'percentProfit'        => $profit['simple'],
            'percentProfitComplex' => $profit['complex'],
            'firstPriceDate'       => $analizer->getFirstTradeDate($strategy),
            'lastPriceDate'        => $analizer->getLastTradeDate($strategy),
        ];
    }
}

src/Rottenwood/BarchartBundle/Resources/views/Default/editStrategy.html.twig
{% extends ':Default:layout.html.twig' %}

{% block content %}

    {{ form_start(form) }}

    <div id="strategy">

        <p>{{ form.vars.value.id ? 'Редактирование' : 'Создание новой' }}  торговой стратегии</p>

        <div>
            {{ form_label(form.name) }}
            {{ form_widget(form.name) }}
        </div>
        <div>
            {{ form_label(form.symbol) }}
            {{ form_widget(form.symbol) }}
        </div>
        <div id="strategy-signals" data-prototype="{{ form_widget(form.signals.vars.prototype) | e }}">
            {% for formSignal in form.signals %}
                <div>
                    {{ form_widget(formSignal) }}
                    <div>
                        {% for signalIndicator in formSignal.indicatorValues %}
                            <div>
                                {{ form_widget(signalIndicator) }}
                            </div>
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}
        </div>

        {% if form_errors(form) %}
            <div class="form-error">{{ form_errors(form) }}</div>
        {% endif %}

        {{ form_widget(form.addSignal) }}

        <hr/>

        <p>Параметры стратегии:</p>
        {{ form_row(form.openIfExist) }}
        {{ form_row(form.isPrivate) }}

        <div class="break-20"></div>

        <div>
            {{ form_widget(form.save) }}
        </div>

    </div>
    {{ form_end(form) }}

{% endblock content %}

src/Rottenwood/BarchartBundle/Resources/views/Default/index.html.twig
{% extends ':Default:layout.html.twig' %}

{% block content %}

    <p>Главная страница</p>

    <p><a href="{{ path('analitic.cabinet') }}">Личный кабинет</a></p>
    <p><a href="{{ path('strategy.create') }}">Создание новой стратегии</a></p>

    {% if haveStrategies %}
        <p><a href="{{ path('strategy.list') }}">Список ваших стратегий</a></p>
        <p><a href="{{ path('account.create') }}">Создание нового торгового
                счета</a></p>
        {% if haveAccounts %}
            <p><a href="{{ path('account.list') }}">Список торговых счетов</a></p>
        {% endif %}

    {% endif %}

{% endblock content %}

src/Rottenwood/BarchartBundle/Resources/views/Default/listStrategies.html.twig
{% extends ':Default:layout.html.twig' %}

{% block title %}Список стратегий{% endblock title %}

{% block content %}

    <p>Список ваших торговых стратегий:</p>

    <table id="strategies-list" class="list">
        <thead>
        <tr>
            <td>#</td>
            <td>Название стратегии</td>
            <td>Видимость</td>
            <td></td>
            <td></td>
        </tr>
        </thead>

        <tbody>
        {% for strategy in strategies %}
            <tr>
                <td>{{ strategy.id }}</td>
                <td>
                    {{ strategy.name }}
                </td>
                <td>
                    {{ strategy.isPrivate ? 'только мне' : 'для всех' }}
                </td>
                <td>
                    <a href="{{ path('strategy.edit', {id: strategy.id}) }}">
                        редактировать
                    </a>
                </td>
                <td>
                    <a href="{{ path('strategy.test', {id: strategy.id}) }}">
                        протестировать
                    </a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock content %}

src/Rottenwood/BarchartBundle/Resources/views/Default/showStrategyRating.html.twig
{% extends ':Default:layout.html.twig' %}

{% block title %}Список стратегий{% endblock title %}

{% block content %}

    <p>Список ваших торговых стратегий:</p>

    <table id="strategies-list" class="list">
        <thead>
        <tr>
            <td>#</td>
            <td>Автор</td>
            <td>Название стратегии</td>
            <td>Торговый инструмент</td>
            <td></td>
        </tr>
        </thead>

        <tbody>
        {% for strategy in strategies %}
            <tr>
                <td>{{ strategy.id }}</td>
                <td>
                    {{ strategy.author.username }}
                </td>
                <td>
                    {{ strategy.name }}
                </td>
                <td>
                    {{ strategy.symbol|symbol_name }}
                </td>
                <td>
                    <a href="{{ path('strategy.test', {id: strategy.id}) }}">
                        протестировать
                    </a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock content %}

src/Rottenwood/BarchartBundle/Resources/views/Default/testStrategy.html.twig
{% extends ':Default:layout.html.twig' %}

{% set profit = 0 %}
{% set profitLocal = 0 %}
{% set profitTrades = 0 %}
{% set lossTrades = 0 %}
{% set unclosedTrades = 0 %}

{% block javascript %}
    {# Скрипты для отрисовки графиков #}
    <script type="text/javascript" src="{{ asset('assets/js/chart.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/barchart.js') }}"></script>
{% endblock javascript %}

{% block title %}
    Тестирование стратегии #
    {% if strategyIsPrivate is defined %}
        {{ strategyIsPrivate }}
    {% else %}
        {{ strategy.id }}
    {% endif %}

{% endblock title %}

{% block content %}
    {% if strategyIsPrivate is defined %}
        <div>
            Доступ к стратегии <strong>#{{ strategyIsPrivate }}</strong> ограниен его владельцем.
        </div>
    {% else %}

        {% for trade in trades %}
            {% set profit = profit + trade.profit %}
            {% if not trade.closeDate %}
                {% set unclosedTrades = unclosedTrades + 1 %}
            {% endif %}

            {% if trade.profit > 0 %}
                {% set profitTrades = profitTrades + 1 %}
            {% elseif trade.profit < 0 %}
                {% set lossTrades = lossTrades + 1 %}
            {% endif %}
        {% endfor %}

        {# График доходности стратегии #}
        <canvas id="chart-backtest" width="800" height="300"></canvas>

        <p>
            Тестирование стратегии "<strong>{{ strategy.name }}</strong>"
            (автор: {{ strategy.author.username }})
        </p>

        <p>Торговый инструмент: <strong>{{ strategy.russianSymbolName[strategy.symbol] }}</strong> ({{ strategy
            .symbolName[strategy.symbol] }})
        </p>
        <p>Видимость: {{ strategy.isPrivate ? 'только мне' : 'для всех' }}</p>
        <p>Дата начала тестирования: {{ firstPriceDate|date('Y-m-d H:i') }}</p>
        <p>Дата конца тестирования: {{ lastPriceDate|date('Y-m-d H:i') }}</p>
        <p>Открываются ли параллельные сделки: <strong>{{ strategy.openIfExist ? 'да' : 'нет' }}</strong></p>
        <p>Количество открытых сделок: {{ trades|length }} ({{ unclosedTrades }} незакрытых)</p>
        <p>Количество закрытых сделок: {{ trades|length - unclosedTrades }} ({{ profitTrades }}
            прибыльных, {{ lossTrades }} убыточных)</p>
        <p>Соотношение прибыльных к убыточным: <strong>
                {{ lossTrades ? (profitTrades/lossTrades)|round(2, 'floor') : profitTrades }}
            </strong></p>
        <p>Итоговая прибыль: <strong>{{ profit }}</strong>
            (<strong>{{ percentProfit > 0 ? '+' ~ percentProfit : percentProfit }}%</strong>)</p>
        <p>Итоговая прибыль с учетом рекапитализации:
            <strong>{{ percentProfitComplex > 0 ? '+' ~ percentProfitComplex : percentProfitComplex }}%</strong>
        </p>

        <div class="break-50"></div>

        <p>Сигналы стратегии:</p>
        {% for signal in strategy.signals %}
            <div class="gray-box">
                <p>Направление: {{ signal.direction > 0 ? 'Покупка' : 'Продажа' }}</p>

                {% if signal.stopLoss %}
                    <p>Стоплосс: {{ signal.stopLoss }}$</p>
                {% endif %}

                {% if signal.stopLossPercent %}
                    <p>Стоплосс в процетах: {{ signal.stopLossPercent }}%</p>
                {% endif %}

                {% if signal.takeProfit %}
                    <p>Тейкпрофит: {{ signal.takeProfit }}$</p>
                {% endif %}

                {% if signal.takeProfitPercent %}
                    <p>Тейкпрофит в процетах: {{ signal.takeProfitPercent }}%</p>
                {% endif %}

                {% for indicatorValue in signal.indicatorValues %}
                    <p>
                        Индикатор <strong>"{{ indicatorValue.indicator.name }}"</strong>
                        с параметром <strong>{{ indicatorValue.value|direction_name }}</strong>
                    </p>
                {% endfor %}

            </div>
        {% endfor %}

        <hr/>

        <p>Сделки:</p>

        <table id="trades-list" class="center width-full list">
            <thead>
            <tr>
                <td>#</td>
                <td>Направление</td>
                <td>Дата открытия</td>
                <td>Дата закрытия</td>
                <td>Длительность<br>
                    (час:мин)
                </td>
                <td>Цена открытия</td>
                <td>Цена закрытия</td>
                <td>Прибыль</td>
                <td>Общая прибыль</td>
            </tr>
            </thead>

            <tbody>
            {% set profitPercent = 0 %}
            {% set profitPercentComplex = 100 %}

            {% for trade in trades %}
                {% if trade.profit > 0 %}
                    {% set rowColor = 'green' %}
                {% elseif trade.profit < 0 %}
                    {% set rowColor = 'red' %}
                {% endif %}

                {% if not trade.closeDate %}
                    {% set rowColor = 'yellow' %}
                {% endif %}

                {% set profitLocal = profitLocal + trade.profit %}

                <tr class="{{ rowColor }}">
                    <td>{{ loop.index }}</td>
                    <td>{{ trade.direction > 0 ? 'Покупка' : 'Продажа' }}</td>
                    <td>{{ trade.openDate|date('d-m-Y H-i') }}</td>
                    {% if trade.closeDate %}
                        <td class="close-date" data-date="{{ trade.closeDate|date('d.m') }}">
                            {{ trade.closeDate|date('d-m-Y H-i') }}
                        </td>
                    {% else %}
                        <td></td>
                    {% endif %}
                    <td>
                        {% if trade.closeDate %}
                            {% set tradeInterval = dates_diff(trade.openDate, trade.closeDate) %}
                            {% set tradeIntervalDays = tradeInterval|date('%d') %}
                            {% set tradeIntervalHours = tradeInterval|date('%h') %}
                            {% set tradeIntervalMinutes = tradeInterval|date('%i') %}

                            {% if tradeIntervalDays or tradeIntervalHours or tradeIntervalMinutes %}
                                {% if tradeIntervalDays %}
                                    {{ tradeIntervalDays }} {{ 'day'|transchoice(tradeIntervalDays) }}
                                {% endif %}

                                {% if tradeIntervalHours %}
                                    {{ tradeIntervalHours }} {{ 'hour'|transchoice(tradeIntervalHours) }}
                                {% endif %}

                                {% if tradeIntervalMinutes %}
                                    {{ tradeIntervalMinutes }} {{ 'minute'|transchoice(tradeIntervalMinutes) }}
                                {% endif %}
                            {% endif %}
                        {% else %}
                            открыта
                        {% endif %}
                    </td>
                    <td>{{ trade.open }}</td>
                    <td>
                        {% if trade.close %}
                            {{ trade.close }}
                        {% else %}
                            {{ currentPrice }}
                        {% endif %}

                    </td>
                    <td>
                        {% if not trade.profit %}
                            {% if trade.direction is constant('DIRECTION_BUY', trade) %}
                                {% set tradeProfit = currentPrice - trade.open %}
                            {% else %}
                                {% set tradeProfit = trade.open - currentPrice %}
                            {% endif %}
                        {% endif %}

                        {{ trade.profit ?: tradeProfit|round(2, 'floor') }}
                    </td>
                    <td class="profit-local" data-profit="{{ profitLocal }}">
                        {% if trade.profit %}
                            {% set profitPercent = profitPercent + trade.profit / trade.open * 100 %}
                            {% set profitPercentComplex = profitPercentComplex * (1 + (trade.profit / trade.open * 100) / 100) %}
                        {% else %}
                            {% set profitPercent = profitPercent + tradeProfit / trade.open * 100 %}
                            {% set profitPercentComplex = profitPercentComplex * (1 + (tradeProfit / trade.open * 100) / 100) %}
                        {% endif %}

                        {{ profitLocal }} / {{ profitPercent > 0 ? '+' : '' }}
                        <span>{{ profitPercent|round(2, 'floor') }}</span>% /
                        <strong>
                            {{ profitPercentComplex - 100 > 0 ? '+' : '' }}
                            {{ (profitPercentComplex - 100)|round(2, 'floor') }}%
                        </strong>
                    </td>
                </tr>

                {% if trade.closeDate %}
                    {% set lastTradeDate = trade.closeDate|date('d.m') %}
                    {% set lastTradeProfit = profitPercent %}
                {% endif %}

                {% if loop.last %}
                    <span id="last-trade-data" data-date="{{ lastTradeDate }}"
                          data-profit="{{ lastTradeProfit }}"></span>
                {% endif %}

            {% endfor %}
            </tbody>
        </table>
    {% endif %}


{% endblock content %}

{% block submenu %}
    <p><a href="{{ path('strategy.list') }}">Вернться к списку стратегий</a></p>
{% endblock submenu %}